/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Service = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'provider' : IDL.Principal,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'userType' : IDL.Variant({
    'taker' : IDL.Null,
    'provider' : IDL.Null,
    'both' : IDL.Null,
    'none' : IDL.Null,
  }),
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'receiver' : IDL.Principal,
});
export const ServiceProvider = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'ratings' : IDL.Vec(IDL.Nat),
  'services' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDocument' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'addProvider' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addRating' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeBooking' : IDL.Func([IDL.Text], [], []),
  'findProvidersByService' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessagesWithUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getProviderAvailability' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getProviders' : IDL.Func([], [IDL.Vec(ServiceProvider)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'makeBooking' : IDL.Func([IDL.Text, Time, Time], [], []),
  'registerTaker' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchServicesByKeyword' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Service)],
      ['query'],
    ),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updateAvailability' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Service = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'provider' : IDL.Principal,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'userType' : IDL.Variant({
      'taker' : IDL.Null,
      'provider' : IDL.Null,
      'both' : IDL.Null,
      'none' : IDL.Null,
    }),
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'receiver' : IDL.Principal,
  });
  const ServiceProvider = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'ratings' : IDL.Vec(IDL.Nat),
    'services' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDocument' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'addProvider' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addRating' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeBooking' : IDL.Func([IDL.Text], [], []),
    'findProvidersByService' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessagesWithUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getProviderAvailability' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getProviders' : IDL.Func([], [IDL.Vec(ServiceProvider)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'makeBooking' : IDL.Func([IDL.Text, Time, Time], [], []),
    'registerTaker' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchServicesByKeyword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updateAvailability' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };