/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Message {
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
  'receiver' : Principal,
}
export interface Service {
  'title' : string,
  'duration' : bigint,
  'provider' : Principal,
  'description' : string,
  'price' : bigint,
}
export interface ServiceProvider {
  'contactInfo' : string,
  'name' : string,
  'ratings' : Array<bigint>,
  'services' : Array<string>,
}
export type Time = bigint;
export interface UserProfile {
  'userType' : { 'taker' : null } |
    { 'provider' : null } |
    { 'both' : null } |
    { 'none' : null },
  'contactInfo' : string,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDocument' : ActorMethod<[string, ExternalBlob], undefined>,
  'addProvider' : ActorMethod<[string, string], undefined>,
  'addRating' : ActorMethod<[Principal, bigint, string], undefined>,
  'addService' : ActorMethod<[string, string, bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeBooking' : ActorMethod<[string], undefined>,
  'findProvidersByService' : ActorMethod<[string], Array<string>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessagesWithUser' : ActorMethod<[Principal], Array<Message>>,
  'getProviderAvailability' : ActorMethod<[Principal], Array<string>>,
  'getProviders' : ActorMethod<[], Array<ServiceProvider>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'makeBooking' : ActorMethod<[string, Time, Time], undefined>,
  'registerTaker' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchServicesByKeyword' : ActorMethod<[string], Array<Service>>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'updateAvailability' : ActorMethod<[Array<string>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];